
name: test
on: push
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        # Клонируем репозиторий
        - uses: actions/checkout@v4
        # Устанавливаем Node.js
        - uses: actions/setup-node@v4
        # Ставим зависимости
        - run: make setup

        - run: make lint

        - name: run tests
          run: make test